import type { Collection, Item } from "./types";

export const DEMO_COLLECTIONS: Collection[] = [
  { key: "ML", name: "Machine learning", parentCollection: false },
  { key: "NLP", name: "Language models", parentCollection: "ML" },
  { key: "SCI", name: "History of science", parentCollection: false },
  { key: "READ", name: "Reading list", parentCollection: false },
];

export const DEMO_ITEMS: Item[] = [
  {
    key: "VASW17",
    itemType: "conferencePaper",
    title: "Attention Is All You Need",
    creators: [
      { creatorType: "author", firstName: "Ashish", lastName: "Vaswani" },
      { creatorType: "author", firstName: "Noam", lastName: "Shazeer" },
      { creatorType: "author", firstName: "Niki", lastName: "Parmar" },
      { creatorType: "author", firstName: "Jakob", lastName: "Uszkoreit" },
      { creatorType: "author", firstName: "Llion", lastName: "Jones" },
      { creatorType: "author", firstName: "Aidan N.", lastName: "Gomez" },
      { creatorType: "author", firstName: "Łukasz", lastName: "Kaiser" },
      { creatorType: "author", firstName: "Illia", lastName: "Polosukhin" },
    ],
    date: "2017",
    conferenceName: "Advances in Neural Information Processing Systems",
    pages: "5998–6008",
    url: "https://arxiv.org/abs/1706.03762",
    abstractNote:
      "The Transformer architecture dispenses with recurrence and convolutions, relying entirely on attention to draw global dependencies between input and output.",
    tags: ["transformers", "attention", "nlp"],
    collections: ["ML", "NLP", "READ"],
  },
  {
    key: "DEVL19",
    itemType: "conferencePaper",
    title: "BERT: Pre-training of Deep Bidirectional Transformers for Language Understanding",
    creators: [
      { creatorType: "author", firstName: "Jacob", lastName: "Devlin" },
      { creatorType: "author", firstName: "Ming-Wei", lastName: "Chang" },
      { creatorType: "author", firstName: "Kenton", lastName: "Lee" },
      { creatorType: "author", firstName: "Kristina", lastName: "Toutanova" },
    ],
    date: "2019",
    conferenceName: "NAACL-HLT",
    pages: "4171–4186",
    DOI: "10.18653/v1/N19-1423",
    abstractNote:
      "BERT pre-trains deep bidirectional representations from unlabeled text and can be fine-tuned with one additional output layer.",
    tags: ["bert", "pretraining", "nlp"],
    collections: ["NLP"],
  },
  {
    key: "KRIZ12",
    itemType: "journalArticle",
    title: "ImageNet Classification with Deep Convolutional Neural Networks",
    creators: [
      { creatorType: "author", firstName: "Alex", lastName: "Krizhevsky" },
      { creatorType: "author", firstName: "Ilya", lastName: "Sutskever" },
      { creatorType: "author", firstName: "Geoffrey E.", lastName: "Hinton" },
    ],
    date: "2012",
    publicationTitle: "Communications of the ACM",
    volume: "60",
    issue: "6",
    pages: "84–90",
    DOI: "10.1145/3065386",
    abstractNote:
      "A large, deep convolutional neural network trained on ImageNet achieved a winning top-5 error rate in the ILSVRC-2012 competition.",
    tags: ["cnn", "imagenet", "vision"],
    collections: ["ML", "READ"],
  },
  {
    key: "KING15",
    itemType: "conferencePaper",
    title: "Adam: A Method for Stochastic Optimization",
    creators: [
      { creatorType: "author", firstName: "Diederik P.", lastName: "Kingma" },
      { creatorType: "author", firstName: "Jimmy", lastName: "Ba" },
    ],
    date: "2015",
    conferenceName: "International Conference on Learning Representations",
    url: "https://arxiv.org/abs/1412.6980",
    abstractNote:
      "Adam computes adaptive learning rates for each parameter from estimates of first and second moments of the gradients.",
    tags: ["optimization", "adam"],
    collections: ["ML"],
  },
  {
    key: "MNIH15",
    itemType: "journalArticle",
    title: "Human-level control through deep reinforcement learning",
    creators: [
      { creatorType: "author", firstName: "Volodymyr", lastName: "Mnih" },
      { creatorType: "author", firstName: "Koray", lastName: "Kavukcuoglu" },
      { creatorType: "author", firstName: "David", lastName: "Silver" },
      { creatorType: "author", firstName: "Andrei A.", lastName: "Rusu" },
      { creatorType: "author", firstName: "Joel", lastName: "Veness" },
      { creatorType: "author", firstName: "Marc G.", lastName: "Bellemare" },
      { creatorType: "author", firstName: "Alex", lastName: "Graves" },
      { creatorType: "author", firstName: "Martin", lastName: "Riedmiller" },
      { creatorType: "author", firstName: "Andreas K.", lastName: "Fidjeland" },
      { creatorType: "author", firstName: "Georg", lastName: "Ostrovski" },
      { creatorType: "author", firstName: "Stig", lastName: "Petersen" },
      { creatorType: "author", firstName: "Charles", lastName: "Beattie" },
      { creatorType: "author", firstName: "Amir", lastName: "Sadik" },
      { creatorType: "author", firstName: "Ioannis", lastName: "Antonoglou" },
      { creatorType: "author", firstName: "Helen", lastName: "King" },
      { creatorType: "author", firstName: "Dharshan", lastName: "Kumaran" },
      { creatorType: "author", firstName: "Daan", lastName: "Wierstra" },
      { creatorType: "author", firstName: "Shane", lastName: "Legg" },
      { creatorType: "author", firstName: "Demis", lastName: "Hassabis" },
    ],
    date: "2015",
    publicationTitle: "Nature",
    volume: "518",
    issue: "7540",
    pages: "529–533",
    DOI: "10.1038/nature14236",
    abstractNote:
      "A deep Q-network agent, combining reinforcement learning with deep neural networks, reaches human-level performance on a range of Atari games.",
    tags: ["reinforcement-learning", "dqn"],
    collections: ["ML", "READ"],
  },
  {
    key: "KUHN62",
    itemType: "book",
    title: "The Structure of Scientific Revolutions",
    creators: [{ creatorType: "author", firstName: "Thomas S.", lastName: "Kuhn" }],
    date: "1962",
    publisher: "University of Chicago Press",
    place: "Chicago",
    ISBN: "978-0-226-45808-3",
    abstractNote:
      "Kuhn argues that scientific progress proceeds through paradigm shifts rather than purely incremental accumulation of facts.",
    tags: ["philosophy", "paradigm"],
    collections: ["SCI", "READ"],
  },
  {
    key: "HAWK88",
    itemType: "book",
    title: "A Brief History of Time: From the Big Bang to Black Holes",
    creators: [{ creatorType: "author", firstName: "Stephen", lastName: "Hawking" }],
    date: "1988",
    publisher: "Bantam Books",
    place: "New York",
    ISBN: "978-0-553-38016-3",
    abstractNote:
      "A popular account of cosmology covering the Big Bang, black holes, and the search for a unified theory.",
    tags: ["cosmology", "physics"],
    collections: ["SCI"],
  },
  {
    key: "HOFS79",
    itemType: "book",
    title: "Gödel, Escher, Bach: an Eternal Golden Braid",
    creators: [{ creatorType: "author", firstName: "Douglas R.", lastName: "Hofstadter" }],
    date: "1979",
    publisher: "Basic Books",
    place: "New York",
    ISBN: "978-0-465-02656-2",
    abstractNote:
      "A meditation on formal systems, self-reference, and consciousness, braiding mathematics, art, and music.",
    tags: ["cognition", "formal-systems"],
    collections: ["SCI", "READ"],
  },
  {
    key: "LATM87",
    itemType: "book",
    title: "Science in Action: How to Follow Scientists and Engineers through Society",
    creators: [{ creatorType: "author", firstName: "Bruno", lastName: "Latour" }],
    date: "1987",
    publisher: "Harvard University Press",
    place: "Cambridge, MA",
    ISBN: "978-0-674-79291-3",
    abstractNote:
      "Latour follows the production of scientific facts through laboratories, inscriptions, and networks of allies.",
    tags: ["sts", "actor-network"],
    collections: ["SCI"],
  },
  {
    key: "OPEN23",
    itemType: "preprint",
    title: "GPT-4 Technical Report",
    creators: [{ creatorType: "author", name: "OpenAI" }],
    date: "2023",
    url: "https://arxiv.org/abs/2303.08774",
    abstractNote:
      "A technical report describing GPT-4, a large-scale multimodal model, and evaluations of its capabilities and limitations.",
    tags: ["llm", "gpt-4"],
    collections: ["NLP", "READ"],
  },
  {
    key: "ZOTE25",
    itemType: "webpage",
    title: "Zotero Web API Documentation",
    creators: [{ creatorType: "author", name: "Corporation for Digital Scholarship" }],
    date: "2025",
    websiteTitle: "Zotero",
    url: "https://www.zotero.org/support/dev/web_api/v3/basics",
    abstractNote: "Read request documentation for version 3 of the Zotero Web API.",
    tags: ["api", "documentation"],
    collections: [],
  },
  {
    key: "TURI50",
    itemType: "journalArticle",
    title: "Computing Machinery and Intelligence",
    creators: [{ creatorType: "author", firstName: "A. M.", lastName: "Turing" }],
    date: "1950",
    publicationTitle: "Mind",
    volume: "LIX",
    issue: "236",
    pages: "433–460",
    DOI: "10.1093/mind/LIX.236.433",
    abstractNote:
      "Turing proposes the imitation game as a practical substitute for the question “Can machines think?”",
    tags: ["ai", "philosophy"],
    collections: ["SCI", "ML"],
  },
];
